server:
  port: 8055

es:
  hosts: 192.168.72.128:9200,192.168.72.130:9200
  client:
    connectNum: 10
    connectPerRoute: 50
    connect_timeout_millis: 1000
    socket_timeout_millis: 30000
    connection_request_timeout_millis: 500
    max_conn_per_route: 10
    max_conn_total: 30
