package com.lyq3.elasticsearch.example.common.entity.po;

import java.util.Date;

public class Product {
    /**
     *  产品编号,所属表字段为product.id
     */
    private Integer id;

    /**
     *  产品名称,所属表字段为product.name
     */
    private String name;

    /**
     *  产品唯一码
            根据确定一个产品必须的属性生成一个hashcode,所属表字段为product.unique_code
     */
    private String uniqueCode;

    /**
     *  类目编号,所属表字段为product.category_id
     */
    private Integer categoryId;

    /**
     *  产品共性编号,所属表字段为product.product_general_id
     */
    private Integer productGeneralId;

    /**
     *  产品共性名称,所属表字段为product.product_general_name
     */
    private String productGeneralName;

    /**
     *  生产厂家id,所属表字段为product.factory_id
     */
    private Integer factoryId;

    /**
     *  品牌ID,所属表字段为product.brand_id
     */
    private Integer brandId;

    /**
     *  资质ID,所属表字段为product.cert_id
     */
    private Integer certId;

    /**
     *  产品说明ID,所属表字段为product.description_id
     */
    private Integer descriptionId;

    /**
     *  状态
            0 - 待审核
            1 - 通过审核
            2 - 未通过审核
            3 - 锁定（取消锁定后改为1）,所属表字段为product.status
     */
    private Byte status;

    /**
     *  ,所属表字段为product.lock_reason
     */
    private String lockReason;

    /**
     *  是否删除,所属表字段为product.deleted
     */
    private Boolean deleted;

    /**
     *  创建时间,所属表字段为product.create_time
     */
    private Date createTime;

    /**
     *  更新时间,所属表字段为product.update_time
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unique_code
     *
     * @return the value of product.unique_code
     *
     * @mbggenerated
     */
    public String getUniqueCode() {
        return uniqueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unique_code
     *
     * @param uniqueCode the value for product.unique_code
     *
     * @mbggenerated
     */
    public void setUniqueCode(String uniqueCode) {
        this.uniqueCode = uniqueCode == null ? null : uniqueCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_general_id
     *
     * @return the value of product.product_general_id
     *
     * @mbggenerated
     */
    public Integer getProductGeneralId() {
        return productGeneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_general_id
     *
     * @param productGeneralId the value for product.product_general_id
     *
     * @mbggenerated
     */
    public void setProductGeneralId(Integer productGeneralId) {
        this.productGeneralId = productGeneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_general_name
     *
     * @return the value of product.product_general_name
     *
     * @mbggenerated
     */
    public String getProductGeneralName() {
        return productGeneralName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_general_name
     *
     * @param productGeneralName the value for product.product_general_name
     *
     * @mbggenerated
     */
    public void setProductGeneralName(String productGeneralName) {
        this.productGeneralName = productGeneralName == null ? null : productGeneralName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.factory_id
     *
     * @return the value of product.factory_id
     *
     * @mbggenerated
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.factory_id
     *
     * @param factoryId the value for product.factory_id
     *
     * @mbggenerated
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand_id
     *
     * @return the value of product.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand_id
     *
     * @param brandId the value for product.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cert_id
     *
     * @return the value of product.cert_id
     *
     * @mbggenerated
     */
    public Integer getCertId() {
        return certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cert_id
     *
     * @param certId the value for product.cert_id
     *
     * @mbggenerated
     */
    public void setCertId(Integer certId) {
        this.certId = certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description_id
     *
     * @return the value of product.description_id
     *
     * @mbggenerated
     */
    public Integer getDescriptionId() {
        return descriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description_id
     *
     * @param descriptionId the value for product.description_id
     *
     * @mbggenerated
     */
    public void setDescriptionId(Integer descriptionId) {
        this.descriptionId = descriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.lock_reason
     *
     * @return the value of product.lock_reason
     *
     * @mbggenerated
     */
    public String getLockReason() {
        return lockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.lock_reason
     *
     * @param lockReason the value for product.lock_reason
     *
     * @mbggenerated
     */
    public void setLockReason(String lockReason) {
        this.lockReason = lockReason == null ? null : lockReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.deleted
     *
     * @return the value of product.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.deleted
     *
     * @param deleted the value for product.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}